#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
redirect_info="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "35i\ $redirect_info" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
