#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.html

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
search_str="\tlocation / {"
replace_str="\tadd_header X-Served-By ${HOSTNAME}; \n\n\terror_page 404 /error_404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme:// https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$search_str@$replace_str@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
