#!/usr/bin/env bash
# Bash script that configures a server to the above requirements

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
