#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times using while loop

count=1
while [ $count -le 10 ]
do
	echo "Holberton School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	((count++))
done