#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times using while loop

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
	    echo "Holberton School"
	fi
	((count++))
done