#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times using while loop
hour=0
while [ $hour -le 12 ]
do
	min=1
	echo "Hour: $hour"
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done