#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file.
# Bash script should check if the file exists and print
# if the file exists: holbertonschool file exists 
# if the file does not exist: holbertonschool file does not exist
# the file exists, print
# if the file is empty: holbertonschool file is empty
# if the file is not empty: holbertonschool file is not empty
# if the file is a regular file: holbertonschool is a regular file
# if the file is not a regular file: (nothing)

f="holbertonschool"
if [ -e $f ]
then
	echo "holbertonschool file exists"
	if [ -s $f ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $f ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi