#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
wget -O fix_lines https://github.com/01Eddie/holberton-system_engineering-devops/blob/main/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
chmod u+x fix_lines
./fix_lines

